export enum EventStage {
  WAITING_FOR_TEAMS = 'WAITING_FOR_TEAMS',
  CHECKIN = 'CHECKIN',
  QUALIFICATIONS = 'QUALIFICATIONS',
  ALLIANCE_SELECTION = 'ALLIANCE_SELECTION',
  ELIMS = 'ELIMS',
  TEARDOWN = 'TEARDOWN'
}

export const STAGE_TOPIC = 'stage'
