name: Publish
on:
  push:
    branches:
      - beta
jobs:
  release_and_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn build
        
      - name: Run Semantic Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          if [ "$(cat package.json | jq -r '.version')" = "0.0.1" ]; then
            echo "No change to API interface"
            exit 0
          fi
          docker build . --tag ghcr.io/18x18az/maestro:"$(cat package.json | jq -r '.version')"
          docker push ghcr.io/18x18az/maestro:"$(cat package.json | jq -r '.version')"

      - name: Generate API interface
        run: yarn generate
        
      - name: Publish API interface
        working-directory: ./generated
        # first check if version is 0.0.1, if so skip publish
        run: |
          if [ "$(cat package.json | jq -r '.version')" = "0.0.1" ]; then
            echo "No change to API interface"
            exit 0
          fi
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          yarn build
          yarn publish --access public --non-interactive
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
